### ISSUE TITLE
Turnity Manager class name missing

### ISSUE THREAD

**Issue by ScribeAmanuesis** [BananaHolograma/turnity#3]
**Describe the bug**
When installing the add-on, errors are thrwon saying the TurnityManager class name is missing

**To Reproduce**
Install the add on using the asset library

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: Godot 4.2.1 stable

**Additional context**
Is there additional instruction needed to add TurnityManager as an autoload?

**Comment by BananaHolograma** [comment]
Hi @ScribeAmanuesis Have you activated the plugin?? 
Project Settings -> Plugins 

![image](https://github.com/BananaHolograma/turnity/assets/148471672/dd32ff9e-915d-4bba-b72a-c7c7b0fe9b0a)

**Comment by ScribeAmanuesis** [comment]
That was my bad, I thought I had it enabled
